/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/beethoven.glb --transform --output src/components/models/Beethoven.jsx 
Files: public/models/beethoven.glb [25.72MB] > C:\Users\G\Desktop\project01\src\components\models\beethoven-transformed.glb [2.19MB] (92%)
Author: noe-3d.at (https://sketchfab.com/www.noe-3d.at)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/ludwig-van-beethoven-4b3933ff55b9471aa5a5a742e7b0c74b
Title: Ludwig van Beethoven
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Beethoven(props) {
  const { nodes, materials } = useGLTF('./models/beethoven-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Beethoven_O_Material_u1_v1} position={[0, -8, 0]} rotation={[0.002, -0.007, 3.122]} scale={0.196} />
    </group>
  )
}

useGLTF.preload('./models/beethoven-transformed.glb')
