/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ctirad_and_sarka.glb --transform --output src/components/models/CtiradSarka.jsx 
Files: public/models/ctirad_and_sarka.glb [18.56MB] > C:\Users\G\Desktop\project01\src\components\models\ctirad_and_sarka-transformed.glb [1.84MB] (90%)
Author: Mario_Wallner (https://sketchfab.com/Mario_Wallner)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/vysehrad-statue-of-ctirad-and-sarka-df189775a4da4db79fe7a8ece9641112
Title: Vysehrad - Statue of Ctirad and Šárka
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CtiradSarka(props) {
  const { nodes, materials } = useGLTF('./models/ctirad_and_sarka-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/ctirad_and_sarka-transformed.glb')
