/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/freedom_statue.glb --transform --output src/components/models/Freedom.jsx 
Files: public/models/freedom_statue.glb [6.6MB] > C:\Users\G\Desktop\project01\src\components\models\freedom_statue-transformed.glb [434.62KB] (93%)
Author: Senselab (https://sketchfab.com/senselab)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/freedom-statue-01-f28823a837bd406ab3f8f78452e31020
Title: Freedom Statue 01
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from "three"

export function Freedom(props) {
  const { nodes, materials } = useGLTF('./models/freedom_statue-transformed.glb')
  console.log(materials.lambert5)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model1_lambert5_0.geometry}  position={[0, -11.689, 11.971]} rotation={[-Math.PI / 2, 0, 0]}>
      <meshStandardMaterial
        map={materials.lambert5.map}
        color={materials.lambert5.color ?? "#888888"}
      />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/freedom_statue-transformed.glb')
