/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/walt_mickey.glb --transform --output src/components/models/WaltMickey.jsx 
Files: public/models/walt_mickey.glb [1.92MB] > C:\Users\G\Desktop\project01\src\components\models\walt_mickey-transformed.glb [243KB] (87%)
Author: theWerskyScenario (https://sketchfab.com/derfmode)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walt-mickey-statue-scan-5ccfad24f91c4e61ab92e9dd049ed1a3
Title: Walt & Mickey Statue Scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WaltMickey(props) {
  const { nodes, materials } = useGLTF('./models/walt_mickey-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rebake_main001_0.geometry} material={materials['main.001']} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('./models/walt_mickey-transformed.glb')
